### ISSUE TITLE
Tokenize vue specific attributes under `meta.directive.vue` when having no attribute value

### ISSUE THREAD

**Issue by usernamehw** [vuejs/vetur#1009]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win 10
- Vetur version: 0.14.3
- VS Code version: 1.29.1

## Problem

Having different color for vue-specific attributes:
```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "meta.directive.vue entity.other.attribute-name.html",
            "settings": {
                "foreground": "#e90"
            }
        }
    ],
}
```
Some of them are not colorized because of the missing `=` after the attribute.
```vue
<template>
    <div>
        <div @click.prevent></div>
        <div @click.stop></div>
        <div v-on:click.stop></div>
        <div v-on:click.prevent></div>

        <form v-on:submit.prevent></form>
        <!-- ... -->
    </div>
</template>
```
It would be nice if colorization made `=` optional and worked for every case.

**Comment by usernamehw** [comment]
@octref, you've missed an issue.

**Comment by octref** [comment]
Sorry, I had been busy and traveling. Let me get back to this...

**Comment by roydukkey** [comment]
I also would like to see this improvement and be able to target each of the pieces separately.

```
        <div @click.prevent></div>
        <div @click.stop></div>
        <div v-on:click.stop></div>
        <div v-on:click.prevent></div>

        <form v-on:submit.prevent></form>
```

For example, each of these would be targeted by different scopes. Something like this.

1. `@`, `:` scoped as some sort of `symbol`, `operator`, or ...
2. `v-on` scoped as `attribute.directive`
3. `click` scoped as `attribute.name`
4. `stop` scoped as `attribute.other`
