### ISSUE TITLE
Using vue-meta in typescript causing vetur to trigger false-positive errors

### ISSUE THREAD

**Issue by yekver** [vuejs/vetur#1344]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.21.0
- VS Code version: 1.35.1

## Problem
Main error:
```
Object literal may only specify known properties, and 'metaInfo' does not exist in type 'ComponentOptions<{ deviceType: DeviceType; isDesktop: boolean; isTablet: boolean; isMobile: boolean; } & Record<never, any> & Vue, DefaultData<{ deviceType: DeviceType; isDesktop: boolean; isTablet: boolean; isMobile: boolean; } & Record<...> & Vue>, DefaultMethods<...>, DefaultComputed, PropsDefinition<...>, Record...'.Vetur(2345)
```

and a lot of errors in `computed` and `methods` sections like this:
```
Property '$store' does not exist on type '{ ... }'. Vetur(2339)
...
Property 'deviceType' does not exist on type '{ ... }'.Vetur(2339)
```

As you can see on this gif we have a lot of false-positive (`tsc` compiles just fine) errors that disappear after commenting the line with declaring `metaInfo` option
![ScreenRecording2019-06-27at2](https://user-images.githubusercontent.com/1935877/60291966-c71dc480-9924-11e9-9eb7-1a91ed213a36.gif)

## Reproducible Case

Just try to use [vue-meta](https://github.com/nuxt/vue-meta) with typescript Vue components (`<script lang="ts">...</script>`)

**Comment by ktsn** [comment]
I suspect the problem comes from other package or configuration than Vetur. In fact, there are no problem when I try vue-meta in my local.
If you really think this is a bug of Vetur, please provide self-contained reproduction.

**Comment by yekver** [comment]
Seems like that the problem appears only if you define components with `Vue.extend`:
```javascript
<script lang="ts">
   export default Vue.extend({ ... });
</script>
```
Then all vetur errors will be look like you using typescript without `Vue.extend` and there is no info about computed props and store.

**Comment by ktsn** [comment]
It's not the case on my side, I've checked that there is no problem with `Vue.extend`.
It would be appreciated if you provide self-contained reproduction (example GitHub repo producing the error, etc.)

**Comment by yekver** [comment]
I've created a repro here: https://github.com/yekver/ts_vue-meta
You can see this bug in `src/App.vue`.

**Comment by ktsn** [comment]
Because you are not importing `vue-meta` in any TS file in your project. You need to add import statement for `vue-meta` to load its typing.

```ts
// Add import statement in your ts.
import 'vue-meta'
```
