### ISSUE TITLE
The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.Vetur(1343)

### ISSUE THREAD

**Issue by UUmaGii** [vuejs/vetur#3708]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version:0.37.3 

## Problem

i use "npm init vue@latest" init a vue project,this project has config esnext in tsconfig , but still has an alarm
```
The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.Vetur(1343)
```
this is my code
![image](https://github.com/vuejs/vetur/assets/32239680/c1717700-c9e1-41be-9ba3-1827b9c2c1b5)

The above code can run normally, it seems like that vetur can't identify this grammar, but I hope Vetur doesn't give an alarm prompt

**Comment by UUmaGii** [comment]
this is vue project default-tsconfig.node.json
{
  "extends": "@tsconfig/node18/tsconfig.json",
  "include": ["vite.config.*", "vitest.config.*", "cypress.config.*", "playwright.config.*"],
  "compilerOptions": {
    "composite": true,
    "module": "esnext",
    "types": ["node"]
  }
}

**Comment by busyhe** [comment]
VSCode select Typescript Version to Workspace version

**Comment by UUmaGii** [comment]
这是来自QQ邮箱的假期自动回复邮件。
您好，你的邮件已经送达，我看到后会尽快回复。
