### ISSUE TITLE
Proper support for meta-languages

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vetur#796]
* [x] I have searched through existing issues
* [x] I have read through [docs](https://vuejs.github.io/vetur)
* [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Any
- Vetur version: 0.12.2
- VS Code version: 1.24.0-insider

## Request

One of the great (but mostly unfulfilled) promises of Vue's single file components is the ability to use whatever meta-languages you want. Getting proper tooling for `.vue` files is currently difficult. Some things are only achievable in Sublime Text, and others are only achievable in VS Code. No one has successfully created the ✨ *perfect* ✨ Vue dev environment.

One major step forward towards that would be for Vetur to adopt support for all major meta-languages. I'll let you decide what you consider to be "major". However I would think the more things you can support out of the box, the better the experience of the end user of Vetur.

The screenshot below is ordered by popularity (scss, sass, less, stylus/stylus). You'll find that the second most popular meta-language has very weak support, and in fact what support there is seems somewhat random.

![meta languages example](https://user-images.githubusercontent.com/4629794/40191996-1976d3be-59d1-11e8-966d-1369b0b5456c.png)

This is just in regards to styling meta-languages, but the same concept should be applied to template and script metalanguages as well.

It would be nice for this to be acknowledged as a concern, given whatever level of priority it warrants or placed on a roadmap.

**Comment by octref** [comment]
Sass Autocompletion / ColorPicker: This requires a sass Language Server, which no one has now, and I do not have time to build one.

Stylus Color: https://github.com/vuejs/vetur/issues/856
